name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["CI Workflow"]
    types:
      - completed
    branches:
      - main

jobs:
  docker_image:
    name: Build and Push Docker-Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Log in to DockerHub with API Key
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_API_KEY }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ci-jugurtha-samy:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ci-jugurtha-samy:${{ github.sha }}
